### ISSUE TITLE
Make TOC header level aware and collapsable

### ISSUE THREAD

**Issue by as-iotex** [iotexproject/dev-portal-content#5]
If the article contains a lot of headers, then the table of contents becomes too big.
At the moment all the headers in the markdown file are "flattened". Hence they use a lot of vertical space, making the left side panel vertically scrollable.
It would be great if the left panel could show headers indented by header level. And also make them collapsable.
See an example of this issue in https://developers.iotex.io/posts/deploy-a-machinefi-dapp

**Comment by simonerom** [comment]
@nicky-ru ip to what level headers are displayed?

**Comment by nicky-ru** [comment]
fixed
